"""Discord webhook notifier.

Uses Discord's incoming-webhook format — a JSON POST with a single
``embeds`` entry.  No bot token required.
"""

from __future__ import annotations

from typing import Any

import httpx
from loguru import logger

from quell.config.schema import DiscordNotifierConfig
from quell.memory.models import Incident
from quell.notifiers.base import Notifier
from quell.notifiers.formatting import build_summary
from quell.utils.errors import NotifierError

_TIMEOUT_SECONDS = 8.0


class DiscordNotifier(Notifier):
    """Post incident summaries to a Discord incoming webhook."""

    def __init__(self, config: DiscordNotifierConfig) -> None:
        if not config.webhook_url:
            raise NotifierError(
                "Discord notifier missing webhook_url. Run "
                "`quell init` to store one in the OS keychain, or set it "
                "via keyring under quell/discord -> webhook_url."
            )
        self._config = config

    async def notify(self, incident: Incident) -> None:
        payload = self._build_payload(incident)
        try:
            async with httpx.AsyncClient(timeout=_TIMEOUT_SECONDS) as client:
                resp = await client.post(self._config.webhook_url, json=payload)
            if resp.status_code >= 400:
                logger.warning(
                    "discord notifier: HTTP {} -- body={!r}",
                    resp.status_code,
                    resp.text[:200],
                )
        except httpx.HTTPError as exc:
            logger.warning("discord notifier: network error -- {}", exc)

    @staticmethod
    def _build_payload(incident: Incident) -> dict[str, Any]:
        summary = build_summary(incident)
        # Discord expects decimal colour; convert from "#RRGGBB".
        colour = int(summary.severity_color.lstrip("#"), 16)
        fields = [
            {"name": "Status", "value": summary.status, "inline": True},
            {"name": "Severity", "value": summary.severity_label, "inline": True},
            {
                "name": "Occurrences",
                "value": str(summary.occurrence_count),
                "inline": True,
            },
        ]
        if summary.fix_pr_url:
            fields.append(
                {
                    "name": "Proposed fix",
                    "value": f"[Draft PR]({summary.fix_pr_url})",
                    "inline": False,
                }
            )
        embed: dict[str, Any] = {
            "title": summary.title,
            "description": f"**Root cause**\n{summary.root_cause}",
            "color": colour,
            "fields": fields,
            "footer": {"text": "Generated by Quell -- draft PR, never auto-merged."},
        }
        return {"embeds": [embed]}


__all__ = ["DiscordNotifier"]
