"""Slack webhook notifier.

Uses Slack's incoming-webhook format — a JSON POST with ``blocks``
that render as a rich-text card.  No bot token required; the webhook
URL is the only auth material and is loaded from the OS keychain.
"""

from __future__ import annotations

from typing import Any

import httpx
from loguru import logger

from quell.config.schema import SlackNotifierConfig
from quell.memory.models import Incident
from quell.notifiers.base import Notifier
from quell.notifiers.formatting import build_summary
from quell.utils.errors import NotifierError

_TIMEOUT_SECONDS = 8.0


class SlackNotifier(Notifier):
    """Post incident summaries to a Slack incoming webhook."""

    def __init__(self, config: SlackNotifierConfig) -> None:
        if not config.webhook_url:
            raise NotifierError(
                "Slack notifier missing webhook_url. Run "
                "`quell init` to store one in the OS keychain, or set it "
                "via keyring under quell/slack -> webhook_url."
            )
        self._config = config

    async def notify(self, incident: Incident) -> None:
        payload = self._build_payload(incident)
        try:
            async with httpx.AsyncClient(timeout=_TIMEOUT_SECONDS) as client:
                resp = await client.post(self._config.webhook_url, json=payload)
            if resp.status_code >= 400:
                logger.warning(
                    "slack notifier: HTTP {} -- body={!r}",
                    resp.status_code,
                    resp.text[:200],
                )
        except httpx.HTTPError as exc:
            logger.warning("slack notifier: network error -- {}", exc)

    @staticmethod
    def _build_payload(incident: Incident) -> dict[str, Any]:
        summary = build_summary(incident)
        fields = [
            {"type": "mrkdwn", "text": f"*Status*\n{summary.status}"},
            {"type": "mrkdwn", "text": f"*Severity*\n{summary.severity_label}"},
            {"type": "mrkdwn", "text": f"*Occurrences*\n{summary.occurrence_count}"},
        ]
        if summary.fix_pr_url:
            fields.append(
                {
                    "type": "mrkdwn",
                    "text": f"*Proposed fix*\n<{summary.fix_pr_url}|Draft PR>",
                }
            )

        blocks: list[dict[str, Any]] = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": summary.title},
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Root cause*\n{summary.root_cause}",
                },
            },
            {"type": "section", "fields": fields},
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by Quell -- draft PR, never auto-merged.",
                    }
                ],
            },
        ]
        return {"text": summary.title, "blocks": blocks}


__all__ = ["SlackNotifier"]
