"""Telegram Bot API notifier.

Uses the public ``api.telegram.org/bot<token>/sendMessage`` endpoint.
Expects the bot to be an admin (or at least a member) of the chat
identified by ``chat_id``.
"""

from __future__ import annotations

import httpx
from loguru import logger

from quell.config.schema import TelegramNotifierConfig
from quell.memory.models import Incident
from quell.notifiers.base import Notifier
from quell.notifiers.formatting import build_summary
from quell.utils.errors import NotifierError

_API_BASE = "https://api.telegram.org"
_TIMEOUT_SECONDS = 8.0


class TelegramNotifier(Notifier):
    """Post incident summaries to a Telegram chat via a bot token."""

    def __init__(self, config: TelegramNotifierConfig) -> None:
        if not config.bot_token:
            raise NotifierError(
                "Telegram notifier missing bot_token. Store one in the "
                "OS keychain under quell/telegram -> bot_token."
            )
        if not config.chat_id:
            raise NotifierError(
                "Telegram notifier missing chat_id. Set it in .quell/config.toml."
            )
        self._config = config
        self._endpoint = f"{_API_BASE}/bot{config.bot_token}/sendMessage"

    async def notify(self, incident: Incident) -> None:
        text = self._build_text(incident)
        payload = {
            "chat_id": self._config.chat_id,
            "text": text,
            "parse_mode": "MarkdownV2",
            "disable_web_page_preview": True,
        }
        try:
            async with httpx.AsyncClient(timeout=_TIMEOUT_SECONDS) as client:
                resp = await client.post(self._endpoint, json=payload)
            if resp.status_code >= 400:
                logger.warning(
                    "telegram notifier: HTTP {} -- body={!r}",
                    resp.status_code,
                    resp.text[:200],
                )
        except httpx.HTTPError as exc:
            logger.warning("telegram notifier: network error -- {}", exc)

    @staticmethod
    def _build_text(incident: Incident) -> str:
        summary = build_summary(incident)

        # Telegram's MarkdownV2 requires escaping every one of:
        # _ * [ ] ( ) ~ ` > # + - = | { } . !
        def esc(text: str) -> str:
            specials = r"_*[]()~`>#+-=|{}.!"
            return "".join("\\" + c if c in specials else c for c in text)

        status_line = (
            f"Status: {esc(summary.status)} "
            f"\\| Severity: {esc(summary.severity_label)} "
            f"\\| Occurrences: {summary.occurrence_count}"
        )
        lines = [
            f"*{esc(summary.title)}*",
            "",
            f"*Root cause:* {esc(summary.root_cause)}",
            "",
            status_line,
        ]
        if summary.fix_pr_url:
            lines.append(f"Proposed fix: [Draft PR]({summary.fix_pr_url})")
        lines.append("")
        lines.append(esc("Generated by Quell -- draft PR, never auto-merged."))
        return "\n".join(lines)


__all__ = ["TelegramNotifier"]
