#!/usr/bin/env python3
"""Generate ``docs/commands.md`` from the Typer app.

Walks the Click introspection tree, formats each command as a Markdown
section with its flags, examples, and help text, and writes the result
to ``docs/commands.md``. Re-run after every CLI surface change so the
doc stays in lock-step with the actual command tree.

Usage::

    python scripts/gen_commands_md.py            # regenerate in place
    python scripts/gen_commands_md.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

# Make `quell` importable when running from the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from quell.interface import cli  # noqa: F401, E402 — registers commands
from quell.interface.help_json import _command_info_dict  # noqa: E402
from quell.interface.main import app  # noqa: E402

_DOC_PATH = _REPO_ROOT / "docs" / "commands.md"

_HEADER = """\
# Quell CLI reference

> Auto-generated by `scripts/gen_commands_md.py` from the live Typer
> app. Re-run the script after any CLI surface change. Hand edits will
> be overwritten — adjust docstrings or `Examples:` blocks in
> `quell/interface/*.py` and regenerate.

"""


def _is_resource(info: dict[str, Any]) -> bool:
    """A resource sub-app has nested ``commands`` (e.g. ``incident``)."""
    return bool(info.get("commands"))


def _summary(info: dict[str, Any]) -> str:
    """Pull the first non-empty line from a command's help text."""
    raw = (info.get("help") or "").strip()
    if not raw:
        return ""
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _format_param(param: dict[str, Any]) -> str:
    """Render one option / argument row for a flag table."""
    opts = " / ".join(f"`{o}`" for o in param.get("opts") or [])
    if not opts:
        # Positional argument — fall back to the param name.
        opts = f"`{param.get('name', '')}`"
    type_name = (param.get("type") or {}).get("name", "")
    default = param.get("default")
    default_str = "" if default in (None, False, []) else f"`{default}`"
    help_text = (param.get("help") or "").strip().replace("|", "\\|")
    return f"| {opts} | {type_name} | {default_str} | {help_text} |"


def _format_command(info: dict[str, Any], heading: str) -> list[str]:
    """Render a single command (no nested resources) as Markdown."""
    lines: list[str] = []
    lines.append(f"### {heading}")
    lines.append("")

    summary = _summary(info)
    if summary:
        lines.append(summary)
        lines.append("")

    params = [p for p in (info.get("params") or []) if not p.get("hidden")]
    if params:
        lines.append("| Flag | Type | Default | Description |")
        lines.append("|---|---|---|---|")
        lines.extend(_format_param(p) for p in params)
        lines.append("")

    # Pull the ``Examples:`` block out of the docstring if the command
    # author wrote one (Phase 5.2 added these).
    examples = _extract_examples(info.get("help") or "")
    if examples:
        lines.append("**Examples:**")
        lines.append("")
        lines.append("```")
        lines.extend(examples)
        lines.append("```")
        lines.append("")

    return lines


def _extract_examples(help_text: str) -> list[str]:
    """Return the lines of the ``Examples:`` block, stripped of indent."""
    out: list[str] = []
    in_block = False
    for line in help_text.splitlines():
        stripped = line.strip()
        if not in_block:
            if stripped.lower().startswith("examples:"):
                in_block = True
            continue
        if not stripped:
            # Blank line — examples blocks end at first blank after content.
            if out:
                break
            continue
        out.append(stripped)
    return out


def _format_resource(name: str, info: dict[str, Any]) -> list[str]:
    """Render a resource sub-app section with each verb as a sub-section."""
    lines: list[str] = []
    lines.append(f"## `{name}` resource")
    lines.append("")
    summary = _summary(info)
    if summary:
        lines.append(summary)
        lines.append("")

    for verb_name, verb_info in sorted((info.get("commands") or {}).items()):
        lines.extend(_format_command(verb_info, f"`quell {name} {verb_name}`"))
    return lines


def render() -> str:
    """Render the full Markdown reference."""
    root = _command_info_dict(app, name="quell")

    parts: list[str] = [_HEADER]

    parts.append("## Global verbs\n")
    commands = root.get("commands") or {}
    global_verbs = {n: i for n, i in commands.items() if not _is_resource(i)}
    for name, info in sorted(global_verbs.items()):
        parts.extend(_format_command(info, f"`quell {name}`"))

    parts.append("\n## Resources\n")
    resources = {n: i for n, i in commands.items() if _is_resource(i)}
    for name, info in sorted(resources.items()):
        parts.extend(_format_resource(name, info))

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/commands.md is out of sync with the CLI.",
    )
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = _DOC_PATH.read_text(encoding="utf-8") if _DOC_PATH.exists() else ""
        if current != rendered:
            sys.stderr.write(
                "docs/commands.md is out of sync — run "
                "`python scripts/gen_commands_md.py` to regenerate.\n"
            )
            return 1
        return 0

    _DOC_PATH.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {_DOC_PATH.relative_to(_REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
