#!/usr/bin/env python3
"""Render a Homebrew formula for the published Quell sdist.

Reads the template at ``packaging/homebrew/quell.rb``, swaps the
``url`` and ``sha256`` for the values discovered on PyPI, and writes
the result to a destination file (typically the tap repo's
``Formula/quell.rb``).

Resource blocks for the Python dependency closure are NOT inserted
here — Homebrew's audit pass tolerates a virtualenv install with a
bare ``pip install`` fallback, and the ``poet``-based resource
generation is brittle enough that we leave it as a manual
post-publish step until somebody asks for full bottling.

Usage:
  python scripts/render_homebrew_formula.py \\
      --version 0.2.0 \\
      --url     https://files.pythonhosted.org/.../quell-agent-0.2.0.tar.gz \\
      --sha256  abc123... \\
      --in      packaging/homebrew/quell.rb \\
      --out     /tmp/quell.rb
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def render(template: str, version: str, url: str, sha256: str) -> str:
    """Return the formula text with url + sha256 replaced.

    The template's ``url`` / ``sha256`` lines are matched by their
    keyword (the placeholder values vary across releases), so this
    keeps working as long as the formula has a single top-level
    ``url`` and a single top-level ``sha256``.
    """
    text = re.sub(
        r'(?m)^(\s*url\s+)"[^"]+"',
        rf'\1"{url}"',
        template,
        count=1,
    )
    text = re.sub(
        r'(?m)^(\s*sha256\s+)"[^"]+"',
        rf'\1"{sha256}"',
        text,
        count=1,
    )
    # Replace the template's "This is a TEMPLATE, not yet live..."
    # preamble (multi-paragraph) with a single attribution line so the
    # rendered formula doesn't read like work-in-progress.
    text = re.sub(
        r"# This is a TEMPLATE.*?# Once live, users install with:\n",
        (
            f"# Generated by scripts/render_homebrew_formula.py at release time (v{version}).\n"
            "# Source template lives at packaging/homebrew/quell.rb in the main repo.\n"
            "#\n"
            "# Users install with:\n"
        ),
        text,
        count=1,
        flags=re.DOTALL,
    )
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--url", required=True)
    parser.add_argument("--sha256", required=True)
    parser.add_argument("--in", dest="input", required=True, type=Path)
    parser.add_argument("--out", dest="output", required=True, type=Path)
    args = parser.parse_args()

    if len(args.sha256) != 64 or not re.fullmatch(r"[0-9a-f]+", args.sha256):
        print(f"error: sha256 '{args.sha256}' is not a 64-char hex digest", file=sys.stderr)
        return 2

    template = args.input.read_text()
    rendered = render(template, args.version, args.url, args.sha256)
    args.output.write_text(rendered)
    print(f"Wrote {args.output} (v{args.version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
